Repository antimatter-dao/bas-genesis-config, pull requests merged in 2022-08, with the labels that each got.

#1 Upgrade genesis submodule to antimatter-dao
  create-genesis.go
  go.mod
Labels: good first issue

#2 Update module config
  create-genesis.go
  go.mod
  go.sum
Labels: bug fix

#3 Change deployer mappings to public access
  contracts/DeployerProxy.sol
Labels: enhancement

#4 Fix go mod failure when go version bump from 1.16 to 1.17
  go.mod
  go.sum
Labels: bug fix

#5 Add vault contract
  contracts/ChainConfig.sol
  contracts/DeployerProxy.sol
  contracts/Governance.sol
  contracts/InjectorContextHolder.sol
  contracts/RuntimeUpgrade.sol
  contracts/SlashingIndicator.sol
  contracts/Staking.sol
  contracts/StakingPool.sol
  contracts/SystemReward.sol
  contracts/Vault.sol
  contracts/interfaces/IVault.sol
  contracts/tests/FakeChainConfig.sol
  contracts/tests/FakeDeployerProxy.sol
  contracts/tests/FakeGovernance.sol
  contracts/tests/FakeRuntimeUpgrade.sol
  contracts/tests/FakeSlashingIndicator.sol
  contracts/tests/FakeStaking.sol
  contracts/tests/FakeStakingPool.sol
  contracts/tests/FakeStakingWithMethod.sol
  contracts/tests/FakeSystemReward.sol
  contracts/tests/StorageLayoutChecker.sol
  create-genesis.go
  yarn.lock
Labels: enhancement

#6 Update vault contract
  contracts/Vault.sol
  yarn.lock
Labels: bug fix

#7 Add vault contract
  contracts/Vault.sol
Labels: bug fix

#9 Add vault contract bridge script
  add-vault-bridging.js
Labels: enhancement

#8 Update vault contract
  contracts/Vault.sol
Labels: enhancement
